# Generated by Django 5.0.4 on 2024-05-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, default='unpaid', max_length=70),
        ),
    ]
