# Generated by Django 5.0.3 on 2024-05-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription_plan',
        ),
    ]
