# Generated by Django 5.0.4 on 2024-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_subscription_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
