# Generated by Django 5.0.3 on 2024-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_id',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
