# Generated by Django 5.0.4 on 2024-05-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.subscriptionplan'),
        ),
    ]
