# Generated by Django 5.0.4 on 2024-05-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_subscription_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.subscriptionplan'),
        ),
    ]
